### ISSUE TITLE
Review of protobuf user-end APIs

### ISSUE THREAD

**Issue by Aniket21mathur** [Aniket21mathur/Chapel-protobuf#27]
We now have a Chapel plugin for the `protoc` compiler and a user module for supporting protobuf operations. The[ pull request](https://github.com/chapel-lang/chapel/pull/16105) for integrating the work with chapel `master` is under review.

Meanwhile, it is important that we have a good feedback on the names of user-end functions. For now, the generated Chapel code for a message includes 2 user-facing methods-

- `writeToOutputFile(ch)` - This function enables the user to serialize proto messages into protobuf binary wire format through a writing channel to an output file.

- `parseFromInputFile(ch)` - This function enables the user to parse proto messages from an input file through a reading channel.

Example usage of the methods through a generated `chpl` file from a source `proto` file.

_example.proto_(source `proto` file)

```proto
syntax = "proto3";

message exampleMessage {
  int64 testField = 1;
}
```
_example.chpl_ (Mock generated chapel file)

```chpl
module example {  // Generated by the protocol buffer compiler.
  ...
  record exampleMessage {
    var testField: int(64);
    proc writeToOutputFile(ch) throws { ... }
    proc parseFromInputFile(ch) throws { ... }
  }
}
```
_write.chpl_(code written by a user to set message field values and serialize these to byte stream)

```chpl
use example;
use IO;

var file = open("out", iomode.cw);
var writingChannel = file.writer();

var messageObj: exampleMessage;
messageObj.testField = 9223;

messageObj.writeToOutputFile(writingChannel);
```
_read.chpl_(code written by another user to parse the input  byte stream and access the set message field values )

```chpl
use example;
use IO;

var messageObj: exampleMessage;
var file = open("out", iomode.r);
var readingChannel = file.reader();

messageObj.parseFromInputFile(readingChannel);

writeln(messageObj.testField == 9223); // Prints true
```
What names should we use for the methods currently called `writeToOutputFile` and `parseFromInputFile` in Chapel for writing and parsing respectively?

Common method names used by other languages are -

| **Language** | **Write function** | **Parse function** |
| ------------- | ------------- | ------------- |
| **C++**  | SerializeToOstream  | ParseFromIstream |
| **C#**  | WriteTo  | ParseFrom |
| **Python**  | SerializeToString | ParseFromString |
| **JAVA**  | writeTo  | parseFrom |

**Comment by mppf** [comment]
> For now, we have 2 user exposed functions through the generated file-

Let this say something about them being methods on messages - e.g. "For now, the generated Chapel code for a message includes 2 user-facing methods"

**Comment by mppf** [comment]
I think the example is showing not quite what we need it to. It shows what your work does, but for the API review, we need it to show what it looks like to use it from a user's viewpoint.

So my advice would be to keep the .proto file, delete most of the function bodies in the generated code - just show that `exampleMessage` is a record with the two methods in questions (and put a comment or ... in the function bodies to indicate we left them out). Then, add another .chpl file showing how a user might save a message to a file or read a message from a file using the generated message record.

**Comment by Aniket21mathur** [comment]
@mppf I did some modifications, please have a look.

**Comment by mppf** [comment]
@Aniket21mathur - sounds good, now you can remove more from *example.chpl (Mock code)*. I'd suggest removing `var unknownFieldStream: bytes = "";`, simplifying the comments, and trying to make the generated code shown be shorter to help people focus on the immediate question. E.g:

``` chapel
module example {  // Generated by the protocol buffer compiler.
  ...
  record exampleMessage {
    var testField: int(64);
    proc writeToOutputFile(ch) throws { ... }
    proc parseFromInputFile(ch) throws { ... }
  }
}
```


 The other thing I would consider is adjusting the structure a little bit. In particular I think it would be nice to move the question of what other languages call these methods after the example. That will help the section introducing the question be shorter (which is important). If this part is in its own section, it might be nice to create a markdown table for language x (write name, parse name).

I think it's important to also end your issue with a focused question on what the question is. For example, "What names should we use for the methods currently called writeToOutputFile and parseFromInputFile?".

**Comment by Aniket21mathur** [comment]
@mppf - I made the changes!

**Comment by lydia-duncan** [comment]
I think it would be good to give a little more information before the last two example files - I understood what their purpose was, but people less familiar with the project might be a little lost.

**Comment by lydia-duncan** [comment]
I would also put the question about which function name to use prior to the chart with what other languages do, but that's just me :)

**Comment by Aniket21mathur** [comment]
@lydia-duncan I have made some changes, please have a look!

**Comment by lydia-duncan** [comment]
I think that looks great!  I think the next steps together are:
- Copy that text to an issue on the Chapel repository
- Send a mail asking for feedback to the developers mailing list (giving them probably a week to respond and repinging on Tuesday if you haven't heard anything)
- Have Lydia ping some specific members of the Chapel development team (I'm thinking Brad, Ben A, and possibly Vass)

**Comment by Aniket21mathur** [comment]
Cool, just doing that!

**Comment by lydia-duncan** [comment]
Oh, and David Longnecker, since his work with interoperability may cause him to be a client of protobuf

**Comment by Aniket21mathur** [comment]
> Oh, and David Longnecker, since his work with interoperability may cause him to be a client of protobuf

Sounds good :)
