### ISSUE TITLE
Any support for Chapel

### ISSUE THREAD

**Issue by Aniket21mathur** [Aniket21mathur/Chapel-protobuf#31]
> The Any message type lets you use messages as embedded types without having their .proto definition. An Any contains an arbitrary serialized message as bytes, along with a URL that acts as a globally unique identifier for and resolves to that message's type. To use the Any type, you need to import google/protobuf/any.proto.

Proto file ->

```proto
import "google/protobuf/any.proto";

message ErrorStatus {
  string message = 1;
  repeated google.protobuf.Any details = 2;
}
```

**Comment by Aniket21mathur** [comment]
In chapel I was thinking of something like this -> 

`any.proto`

```proto
syntax = "proto3";

import "google/protobuf/any.proto";

package anypackage;

message test{
  google.protobuf.Any anyfield = 1;
}

message test2{
  int64 ifield = 1;
  bool bfield = 2;
}
```
`anypackage.chpl`

```chpl
var anyfield: Any;
...
...
messageAppend(anyfield, 1, binCh);
...
...
anyfield = messageConsume(binCh, Any);
```

`Any` is the default type generated by the compiler for Any message type fields. The user should be allowed to pack any message type with the `anyfield`. For example in Python a user can do something like this -> 

for writing
```python
import any_pb2

anyMessageObj = any_pb2.test()
messageObj = any_pb2.test2()

messageObj.ifield = 4
messageObj.bfield = True

anyMessageObj.anyfield.Pack(messageObj)

print(anyMessageObj.anyfield)

file = open("out", "wb")
file.write(anyMessageObj.SerializeToString())
file.close()
```
The output of the print statement will be->

```shell

type_url: "type.googleapis.com/anypackage.test2"
value: "\010\004\020\001"

```
for reading
```python
import any_pb2

anyMessageObj = any_pb2.test()
messageObj = any_pb2.test2()

file = open("out", "rb")
anyMessageObj.ParseFromString(file.read())
file.close()

anyMessageObj.anyfield.Unpack(messageObj);

print(messageObj.ifield)
```

**Comment by lydia-duncan** [comment]
Python's duck typing doesn't address for me the worries about compilation with this type - an identifier can change its type throughout a Python program, right?  I'd be curious to see how more statically typed languages react.

In order to be certain this was working, I'd expect to see at least one test that uses two different types for Any under the covers (either in the same message or in separate ones).  I could easily see it working fine as long as Any meant a single type, but still have problems when multiple types were used in the same program

**Comment by astatide** [comment]
Out of curiosity, if you change the identifier type, then it wouldn't conform to the message anymore, right?  So in that case I'd just think you'd have to allow it to remain serialized (as bytes or string).  The examples I found online showed people serializing to/from `Any`, but it looked like they had a 'known' message type (and therefore a .proto file, I would think).  \

EDIT: ooof, more coffee.  Yes, I see what you mean, now.  So I would think your message would just have to stay as a string but expose methods for de-serializing based on a passed in message type that is known, possibly?   Hmmm.

**Comment by Aniket21mathur** [comment]
@lydia-duncan @astatide thanks for investigating. I have implemented something out of what we discussed in the last meeting. Please see #33
