### ISSUE TITLE
Specifiy Chapel unique types via protocol buffer files?

### ISSUE THREAD

**Issue by Aniket21mathur** [Aniket21mathur/Chapel-protobuf#4]
> But I think it would be reasonable for users starting from Chapel to want to use Chapel-unique types in ways that get translated appropriately to other languages, and so would want to have a way to represent them in the .proto files. But maybe that's more the compiler interoperability story's job than the job of our protobuf implementation. Do other languages have a way to specify types that are unique to them via protocol buffer files?

@lydia-duncan I will do some research on my side and then we can continue the discussion.

**Comment by Aniket21mathur** [comment]
@lydia-duncan coming to this, what I think is that the starting point is always the `proto` file. We generate a `chpl` file handling the types specified in the `proto` file. Even though when we deal in `chapel`, we revolve around only those types specified that are specified in the `proto` file. As far as I think for this to be possible there has to something like `chapel` to `proto` file, which differs from the concept of protobufs I guess.

Thanks :-)

**Comment by lydia-duncan** [comment]
Okay, sounds good.  Thanks for looking into it!

**Comment by lydia-duncan** [comment]
I think that means this can be closed?

**Comment by Aniket21mathur** [comment]
> I think that means this can be closed?

Yeah!
